diff write/strash01ref.write write/strash01.write
diff write/strash02ref.write write/strash02.write
diff write/strash03ref.write write/strash03.write
diff write/strash04ref.write write/strash04.write
diff write/strash05ref.write write/strash05.write	
diff write/strash06ref.write write/strash06.write
diff write/strash07ref.write write/strash07.write
diff write/strash08ref.write write/strash08.write
diff write/strash09ref.write write/strash09.write
diff write/strash10ref.write write/strash10.write
diff write/opt01ref.write write/opt01.write
diff write/opt02ref.write write/opt02.write
diff write/opt03ref.write write/opt03.write
diff write/opt04ref.write write/opt04.write
diff write/opt05ref.write write/opt05.write
diff write/opt06ref.write write/opt06.write
diff write/sim01ref.write write/sim01.write
diff write/sim02ref.write write/sim02.write
diff write/sim03ref.write write/sim03.write
diff write/sim04ref.write write/sim04.write
diff write/sim05ref.write write/sim05.write
diff write/sim06ref.write write/sim06.write
diff write/sim07ref.write write/sim07.write 
diff write/sim08ref.write write/sim08.write
diff write/sim09ref.write write/sim09.write
diff write/sim10ref.write write/sim10.write
diff write/sim11ref.write write/sim11.write
diff write/sim12ref.write write/sim12.write
diff write/sim13ref.write write/sim13.write
diff write/sim14ref.write write/sim14.write
diff write/sim15ref.write write/sim15.write
diff write/ok01ref.write write/ok01.write
diff write/ok02ref.write write/ok02.write
diff write/ok03ref.write write/ok03.write
diff write/ok04ref.write write/ok04.write
diff write/ok05ref.write write/ok05.write
diff write/ok06ref.write write/ok06.write
diff write/ok07ref.write write/ok07.write
diff write/ok08ref.write write/ok08.write
diff write/ok09ref.write write/ok09.write
diff write/ok10ref.write write/ok10.write
diff write/ok11ref.write write/ok11.write
diff write/flt01ref.write write/flt01.write
diff write/flt02ref.write write/flt02.write
diff write/flt03ref.write write/flt03.write
diff write/flt04ref.write write/flt04.write
diff write/flt05ref.write write/flt05.write
diff write/flt06ref.write write/flt06.write
diff write/flt07ref.write write/flt07.write
diff write/test1ref.write write/test1.write     
diff write/test2ref.write write/test2.write
diff write/cirp-nref.write write/cirp-n.write
diff write/C1355ref.write write/C1355.write
diff write/C17ref.write write/C17.write
diff write/C1908ref.write write/C1908.write
diff write/C3540ref.write write/C3540.write
diff write/C432ref.write write/C432.write
diff write/C432_rref.write write/C432_r.write
diff write/C499ref.write write/C499.write
diff write/C499_rref.write write/C499_r.write
diff write/C5315ref.write write/C5315.write
diff write/C6288ref.write write/C6288.write
diff write/C7552ref.write write/C7552.write
diff write/C880ref.write write/C880.write 
